# ----------- CONFIGURABLE START -----------
title:            "Read This Ting"
description:      "Econoomics Rant"
url:              https://natashating.github.io # domain
signoff:          "Natasha Ting" # Your name
facebook_appid:
google_analytics: UA-171564247-1
share:            true 

paginate: 6
paginate_path: "page:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
