# ----------- CONFIGURABLE START -----------
title:            "Econ Rant"
description:      "Rants from an Econ Junkie"
url:              https://natashating.com # my custom domain
baseurl:          "" # keeping it blank since my site is at the root of your custom domain.
signoff:          "Natasha Ting" # name
facebook_appid:
google_analytics: G-SNR5WKRRF7
share:            true 

plugins:
  - jekyll-redirect-from
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 6
  permalink: "/page:num/"
  sort_field: "date"
  sort_reverse: true

autopages:
  enabled: false
links:
  - name:         Home
    url:          /
    external:     false
  - name:         CV
    url:          /cv/
    external:     false
  - name:         Blog
    url:          /blog/
    external:     false

# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"

# make sure can use kramdown with attribute lists
# like insert class with ![Author](myimg.jpg){: .author-img }
markdown: kramdown
kramdown:
  input: GFM