# ----------- CONFIGURABLE START -----------
title:            "Econ Rant"
description:      "Rants from an Econ Junkie"
url:              https://natashating.com # my custom domain
baseurl:          "" # keeping it blank since my site is at the root of your custom domain.
signoff:          "Natasha Ting" # name
facebook_appid:
google_analytics: UA-171564247-1
share:            true 

paginate: 6
paginate_path: "page:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"

# make sure can use kramdown with attribute lists
# like insert class with ![Author](myimg.jpg){: .author-img }
markdown: kramdown
kramdown:
  input: GFM